### ISSUE TITLE
(Might be) [BUG] "Floating point exception(core dumped)" in LAMMPS during model deviation calculation

### ISSUE THREAD

**Issue by Tianhua-Wang** [deepmodeling/deepmd-kit#2997] opened 2023-11-17 02:22 UTC
### Bug summary

Dear DP-GEN developers,
  I'm trying to train a deep potential model of the LiF solution (i.e., LiF + 63H2O). However, during the model deviation calculations, I encounter a trouble (may be a bug) when performing MD simulations using the LAMMPS package (internally installed in DP-GEN), i.e., LAMMPS reports “Floating point exception(core dumped)” in the output file and the simulation is terminated. This trouble occurs frequently, e.g., only three of the twenty simulations (each 50 ps) can reach normal termination, making the training procedure fragmented. I am wondering if there are any solutions or suggestions? The input and output files of one simulation are updated as below.
  Thank you for your time and I am looking forward to your reply.

### DP-GEN Version

0.11.1

### Input Files, Running Commands, Error Log, etc.

[Example-DP-LMP.zip](https://github.com/deepmodeling/dpgen/files/13386118/Example-DP-LMP.zip)
[graph.000.zip](https://github.com/deepmodeling/dpgen/files/13386435/graph.000.zip)
[graph.001.zip](https://github.com/deepmodeling/dpgen/files/13386436/graph.001.zip)
[graph.002.zip](https://github.com/deepmodeling/dpgen/files/13386439/graph.002.zip)
[graph.003.zip](https://github.com/deepmodeling/dpgen/files/13386440/graph.003.zip)

### Steps to Reproduce

I have updated all input and output files of one simulation as above, and test calculations can be submitted directly.

**Comment by njzjz** [comment] 2023-11-17 19:42
Duplicate of #2668. It was fixed last month.

**Closed by njzjz** 2023-11-17 19:42 UTC
Labels: bug
