### ISSUE TITLE
DP2.1.5_lmp  can not recongize pair_style in  lammps input file

### ISSUE THREAD

**Issue by lizzybai** [deepmodeling/deepmd-kit#2071] opened 2022-11-08 05:59 UTC
### Bug summary

The dp model trained using dpmd-kit 2.1.5. After training 1000000 steps. We got 4 models to run MD. However, the lmp can not recongize the pair style deepmd.

### DeePMD-kit Version

2.1.5

### TensorFlow Version

unknow

### How did you download the software?

conda

### Input Files, Running Commands, Error Log, etc.

error:
pair_style      deepmd ../graph.000.pb ../graph.001.pb ../graph.002.pb ../graph.003.pb  out_freq ${THERMO_FREQ} out_file model_devi.out
pair_style      deepmd ../graph.000.pb ../graph.001.pb ../graph.002.pb ../graph.003.pb  out_freq 10 out_file model_devi.out
**ERROR: Unrecognized pair style 'deepmd' (src/force.cpp:279)**
Last command: pair_style      deepmd ../graph.000.pb ../graph.001.pb ../graph.002.pb ../graph.003.pb  out_freq ${THERMO_FREQ} out_file model_devi.out

![WeChat Image_20221108135907](https://user-images.githubusercontent.com/32284788/200486892-58f19198-21e8-4410-80a6-9ac027a0c9ad.jpg)

### Steps to Reproduce

no

**Comment by AnguseZhang** [comment] 2022-11-08 06:48
You may execute `export LAMMPS_PLUGIN_PATH=/opt/deepmd-kit-2.1.5/lib/deepmd_lmp` and then try again.  Note that change "/opt/deepmd-kit-2.1.5" to your installation path of DeePMD-kit.

**Comment by njzjz** [comment] 2022-11-08 19:18
Duplicate of #1809.

**Closed by njzjz** 2022-11-08 19:18 UTC
Labels: question

**Comment by 13yong** [comment] 2024-07-15 14:13
> You may execute `export LAMMPS_PLUGIN_PATH=/opt/deepmd-kit-2.1.5/lib/deepmd_lmp` and then try again. Note that change "/opt/deepmd-kit-2.1.5" to your installation path of DeePMD-kit.

Hello. I'm having the same issue.
### When I execute `export LAMMPS_PLUGIN_PATH=*/deepmd/lib/deepmd_lmp`, and then execute `lmp -i lmp.in`
The result as below
#### LAMMPS (23 Jun 2022 - Update 4)
#### Open of file */deepmd/lib/deepmd_lmp/dpplugin.so failed: */deepmd/lib/deepmd_lmp/dpplugin.so: undefined symbol: _ZN9LAMMPS_NS5Error4_allERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEiN3fmt6v8_lmp17basic_string_viewIcEENSA_17basic_format_argsINSA_20basic_format_contextINSA_8appenderEcEEEE
#### Loaded 0 plugins from*/deepmd/lib/deepmd_lmp
#### ERROR: Unrecognized pair style 'deepmd' (src/force.cpp:279)
#### Last command: pair_style	deepmd frozen_model.pb


### In addition, I try to execute `export LAMMPS_PLUGIN_PATH=*/deepmd/lib/deepmd_lmp/dpplugin.so` and then execute `lmp -i lmp.in` 
The result as below
#### LAMMPS (23 Jun 2022 - Update 4)
#### Loaded 0 plugins from */deepmd/lib/deepmd_lmp/dpplugin.so
#### ERROR: Unrecognized pair style 'deepmd' (src/force.cpp:279)
#### Last command: pair_style	deepmd frozen_model.pb

## Can you give me some suggestions ?
