### ISSUE TITLE
Aborted when running ABACUS with dp(from DPA-2 finetune)

### ISSUE THREAD

**Issue by ieiue** [deepmodeling/deepmd-kit#4317] opened 2024-11-06 06:54 UTC
### Bug summary

When calculating the vacancy energy of Fe2 and the SIA of Fe256, there are errors.
![Image](https://github.com/user-attachments/assets/105a4f46-de98-4981-9911-9fccee4366e7)
![Image](https://github.com/user-attachments/assets/1a63fa18-d6eb-4795-8dd2-3f3d6bfd1d4b)

### DeePMD-kit Version

v3.0.0a1

### Backend and its version

no tensorflow

### How did you download the software?

Built from source

### Input Files, Running Commands, Error Log, etc.

[Fe2_vacancy.zip](https://github.com/user-attachments/files/17641017/Fe2_vacancy.zip)
[Fe256_SIA.zip](https://github.com/user-attachments/files/17641016/Fe256_SIA.zip)
I failed to upload this potential:
![Image](https://github.com/user-attachments/assets/74d40c88-a9b4-47bf-87e5-c0cf135667f9)

### Steps to Reproduce

All my input files except frozen_model.pth upload to "Input Files, Running Commands, Error Log, etc.*". Then run ABACUS (v.3.8.0).

**Comment by njzjz** [comment] 2024-11-08 20:16
Duplicate of #3969

**Closed by njzjz** 2024-11-08 20:16 UTC
Labels: bug
