### ISSUE TITLE
Why is the ckpt.meta file not generated during the train process using deepmd?

### ISSUE THREAD

**Issue by XuFanffei** [deepmodeling/deepmd-kit#2761] opened 2023-08-27 11:01 UTC
### Summary

The training process uses the official image of the Bohrium platform，there should be no errors during model training.

### DeePMD-kit Version

Deepmd-kit:2.2.1-cuda.11.6

### TensorFlow Version

2.9.0

### Details

The training process uses the official image of the Bohrium platform，there should be no errors during model training.

**Comment by wanghan-iapcm** [comment] 2023-08-28 10:25
please post your input script and command so others can reproduce the issue

**Comment by lzcun** [comment] 2023-08-30 03:57
[machine.txt](https://github.com/deepmodeling/deepmd-kit/files/12471507/machine.txt)
[run_param.txt](https://github.com/deepmodeling/deepmd-kit/files/12471513/run_param.txt)
aboves are scripts of my job, and the input command is:
`nohup dpgen run run_param.json machine.json > job.out 2>&1 &`

**Comment by wanghan-iapcm** [comment] 2023-08-31 05:54
from the provided input script I do not see the problem.
Could you please restore the training environment and try to reproduce the issue?

**Comment by lzcun** [comment] 2023-08-31 06:13
Actually, all the jobs I have down in this  training environment, don't have ckpt.meta files.

**Comment by njzjz** [comment] 2023-09-04 16:18
@lzcun you leaked passwords in the attached file. I removed that file and please reset the password for security.

**Comment by njzjz** [comment] 2023-10-18 18:40
I'll close the issue since it cannot be reproduced.

**Closed by njzjz** 2023-10-18 18:40 UTC
Labels: question, failed to reproduce
