### ISSUE TITLE
[BUG] ERROR: Unrecognized pair style 'deepmd' (src/force.cpp:271)

### ISSUE THREAD

**Issue by r-hou** [deepmodeling/deepmd-kit#2939] opened 2023-10-19 17:56 UTC
### Bug summary

I installed deepmd-kit using the command "conda create -n deepmd-2.2.4-cpu deepmd-kit=2.2.4=*cpu libdeepmd=2.2.4=*cpu lammps -c https://conda.deepmodeling.com -c defaults" and "conda create -n deepmd-1.3.3-cpu deepmd-kit=1.3.3=*cpu libdeepmd=1.3.3=*cpu lammps -c https://conda.deepmodeling.com -c defaults", but the installed lmp does't support deepmd pair style.

### DeePMD-kit Version

2.2.4 and 1.3.3

### TensorFlow Version

2.9.0 and 2.4.1

### How did you download the software?

conda

### Input Files, Running Commands, Error Log, etc.

LAMMPS (2 Aug 2023 - Update 1)
WARNING: Using I/O redirection is unreliable with parallel runs. Better to use the -in switch to read input files. (src/lammps.cpp:537)
OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (src/comm.cpp:98)
  using 1 OpenMP thread(s) per MPI task
Reading data file ...
  triclinic box = (0 0 0) to (39.4221 39.4221 99.4221) with tilt (0 0 0)
  2 by 4 by 7 MPI processor grid
  reading atoms ...
  6144 atoms
  read_data CPU = 0.031 seconds
ERROR: Unrecognized pair style 'deepmd' (src/force.cpp:271)
Last command: pair_style      deepmd ../dp-model.pb  out_freq ${dumpfreq} out_file model_devi.out

### Steps to Reproduce

just follow the example from github

**Comment by njzjz** [comment] 2023-10-19 19:28
The error of v2.2.4 is a duplicate of #1809.

For v1.3.3, you should follow the v1.3.3 documentation instead of the current version.

**Closed by njzjz** 2023-10-19 19:28 UTC
Labels: bug

**Comment by Panacea7** [comment] 2023-11-22 02:53
I'm experiencing the same error as you are.May I ask how you solved it?
