### ISSUE TITLE
[BUG] Error regarding invalid choice `se_uni` for descriptor type in configuration file

### ISSUE THREAD

**Issue by Andy6M** [deepmodeling/deepmd-kit#3622] opened 2024-03-29 11:09 UTC
### Bug summary

Hello,

I'm encountering an issue when trying to run a simulation with DeepMD-kit version 3.0.0a0, using a configuration file inspired by the example provided on [this webpage](https://nb.bohrium.dp.tech/detail/2649266844). However, I've run into an error related to the configuration of the model descriptor.

The error message is as follows:
'dargs.dargs.ArgumentValueError: [at location model/descriptor/list/1] get invalid choice se_uni for flag key type.'

It suggests that there is an invalid choice (`se_uni`) for the descriptor type in my input configuration file (input2.json).

I've attempted to follow the recommendations and documentation available but seem to have missed how to properly specify the descriptor type for my model. I've also checked the documentation at [DeepMD parallelism guide](https://deepmd.rtfd.io/parallelism/) for any clues on adjusting performance settings but couldn't find anything related to this specific error.

Could you please help me understand what might be causing this issue and how to resolve it? Is `se_uni` an outdated or incorrect descriptor type in the version I am using? If so, what would be the correct configuration?

Thank you for your time and assistance.

Best regards,
AndyX

### DeePMD-kit Version

v3.0.0a0

### TensorFlow Version

PyTorch  2.0.0 Python  3.8(ubuntu20.04) Cuda  11.8

### How did you download the software?

Offline packages

### Input Files, Running Commands, Error Log, etc.

{
  "_comment": "that's all",
  "model": {
   "type_embedding": {
    "neuron": [
     8
    ],
    "tebd_input_mode": "concat"
   },
   "type_map": [
    "B","Br","C","Cl","Cu","F","H","I","N","O","P","S"
   ],
   "descriptor": {
    "type": "hybrid",
    "hybrid_mode": "sequential",
    "list": [
     {
      "type": "se_atten",
      "sel": 120,
      "rcut_smth": 8.0,
      "rcut": 9.0,
      "neuron": [
       25,
       50,
       100
      ],
      "resnet_dt": false,
      "axis_neuron": 12,
      "seed": 1,
      "attn": 128,
      "attn_layer": 0,
      "attn_dotr": true,
      "attn_mask": false,
      "post_ln": true,
      "ffn": false,
      "ffn_embed_dim": 1024,
      "activation": "tanh",
      "scaling_factor": 1.0,
      "head_num": 1,
      "normalize": true,
      "temperature": 1.0,
      "add": "concat",
      "pre_add": true,
      "_comment": " that's all"
     },
     {
      "type": "se_uni",
      "sel": 40,
      "rcut_smth": 3.5,
      "rcut": 4.0,
      "nlayers": 12,
      "g1_dim": 128,
      "g2_dim": 32,
      "attn2_hidden": 32,
      "attn2_nhead": 4,
      "attn1_hidden": 128,
      "attn1_nhead": 4,
      "axis_dim": 4,
      "update_h2": false,
      "update_g1_has_conv": true,
      "update_g1_has_grrg": true,
      "update_g1_has_drrd": true,
      "update_g1_has_attn": true,
      "update_g2_has_g1g1": true,
      "update_g2_has_attn": true,
      "attn2_has_gate": true,
      "add_type_ebd_to_seq": false,
      "smooth": true,
      "_comment": " that's all"
     }
    ]
   },
   "fitting_net": {
    "neuron": [
     240,
     240,
     240
    ],
    "resnet_dt": true,
    "seed": 1,
    "_comment": " that's all"
   },
   "_comment": " that's all"
  },
  "learning_rate": {
   "type": "exp",
   "decay_steps": 1,
   "start_lr": 0.0002,
   "stop_lr": 3.51e-08,
   "_comment": "that's all"
  },
  "loss": {
   "type": "ener",
   "start_pref_e": 0.02,
   "limit_pref_e": 1,
   "start_pref_f": 1000,
   "limit_pref_f": 1,
   "start_pref_v": 0,
   "limit_pref_v": 0,
   "_comment": " that's all"
  },
  "training": {
   "training_data": {
    "systems": [
                 "../Dpdata50-Cu/train/c2h4/200395","../Dpdata50-Cu/train/c2h4/200211","../Dpdata50-Cu/train/c2h4/200331","../Dpdata50-Cu/train/c2h4/200031","../Dpdata50-Cu/train/c2h4/200659","../Dpdata50-Cu/train/c2h4/200302","../Dpdata50-Cu/train/c2h4/200816"
    ],
    "batch_size": "auto",
    "_comment": "that's all"
   },
   "validation_data": {
    "systems": [
                 "../Dpdata50-Cu/validation/c2h4/200945","../Dpdata50-Cu/validation/c2h4/200821","../Dpdata50-Cu/validation/c2h4/200170"
    ],
    "batch_size": 1,
    "_comment": "that's all"
   },
   "numb_steps": 200,
   "warmup_steps": 0,
   "gradient_max_norm": 5.0,
   "seed": 10,
   "disp_file": "lcurve.out",
   "disp_freq": 25,
   "save_freq": 200,
   "_comment": "that's all",
   "wandb_config": {
    "wandb_enabled": false,
    "entity": "dp_model_engineering",
    "project": "DPA"
   }
  }
 }

nohup: ignoring input
To get the best performance, it is recommended to adjust the number of threads by setting the environment variables OMP_NUM_THREADS, DP_INTRA_OP_PARALLELISM_THREADS, and DP_INTER_OP_PARALLELISM_THREADS. See https://deepmd.rtfd.io/parallelism/ for more information.
[2024-03-29 18:51:04,978] DEEPMD INFO    DeepMD version: 3.0.0a0
[2024-03-29 18:51:04,979] DEEPMD INFO    Configuration path: input2.json
[2024-03-29 18:51:05,100] DEEPMD INFO     _____               _____   __  __  _____           _     _  _   
[2024-03-29 18:51:05,100] DEEPMD INFO    |  __ \             |  __ \ |  \/  ||  __ \         | |   (_)| |  
[2024-03-29 18:51:05,100] DEEPMD INFO    | |  | |  ___   ___ | |__) || \  / || |  | | ______ | | __ _ | |_ 
[2024-03-29 18:51:05,100] DEEPMD INFO    | |  | | / _ \ / _ \|  ___/ | |\/| || |  | ||______|| |/ /| || __|
[2024-03-29 18:51:05,100] DEEPMD INFO    | |__| ||  __/|  __/| |     | |  | || |__| |        |   < | || |_ 
[2024-03-29 18:51:05,100] DEEPMD INFO    |_____/  \___| \___||_|     |_|  |_||_____/         |_|\_\|_| \__|
[2024-03-29 18:51:05,100] DEEPMD INFO    Please read and cite:
[2024-03-29 18:51:05,100] DEEPMD INFO    Wang, Zhang, Han and E, Comput.Phys.Comm. 228, 178-184 (2018)
[2024-03-29 18:51:05,100] DEEPMD INFO    Zeng et al, J. Chem. Phys., 159, 054801 (2023)
[2024-03-29 18:51:05,100] DEEPMD INFO    See https://deepmd.rtfd.io/credits/ for details.
[2024-03-29 18:51:05,100] DEEPMD INFO    ---------------------------------------------------------------------------
[2024-03-29 18:51:05,100] DEEPMD INFO    installed to:          /root/deepmd-kit/lib/python3.10/site-packages/deepmd
[2024-03-29 18:51:05,101] DEEPMD INFO    source:                
[2024-03-29 18:51:05,101] DEEPMD INFO    source brach:          HEAD
[2024-03-29 18:51:05,101] DEEPMD INFO    source commit:         50a7f35
[2024-03-29 18:51:05,101] DEEPMD INFO    source commit at:      2024-03-03 17:25:20 -0500
[2024-03-29 18:51:05,101] DEEPMD INFO    use float prec:        double
[2024-03-29 18:51:05,101] DEEPMD INFO    build variant:         cuda
[2024-03-29 18:51:05,101] DEEPMD INFO    Backend:               PyTorch
[2024-03-29 18:51:05,101] DEEPMD INFO    PT ver:                v2.0.0.post200-gc263bd43e8e
[2024-03-29 18:51:05,101] DEEPMD INFO    running on:            autodl-container-30634997bd-f9468e4c
[2024-03-29 18:51:05,101] DEEPMD INFO    computing device:      cuda:0
[2024-03-29 18:51:05,101] DEEPMD INFO    CUDA_VISIBLE_DEVICES:  unset
[2024-03-29 18:51:05,101] DEEPMD INFO    Count of visible GPUs: 1
[2024-03-29 18:51:05,101] DEEPMD INFO    num_intra_threads:     0
[2024-03-29 18:51:05,101] DEEPMD INFO    num_inter_threads:     0
[2024-03-29 18:51:05,101] DEEPMD INFO    ---------------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/deepmd-kit/bin/dp", line 10, in <module>
    sys.exit(main())
  File "/root/deepmd-kit/lib/python3.10/site-packages/deepmd/main.py", line 805, in main
    deepmd_main(args)
  File "/root/deepmd-kit/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/root/deepmd-kit/lib/python3.10/site-packages/deepmd/pt/entrypoints/main.py", line 308, in main
    train(FLAGS)
  File "/root/deepmd-kit/lib/python3.10/site-packages/deepmd/pt/entrypoints/main.py", line 244, in train
    config = normalize(config)
  File "/root/deepmd-kit/lib/python3.10/site-packages/deepmd/utils/argcheck.py", line 2505, in normalize
    data = base.normalize_value(data, trim_pattern="_*")
  File "/root/deepmd-kit/lib/python3.10/site-packages/dargs/dargs.py", line 561, in normalize_value
    self.traverse_value(
  File "/root/deepmd-kit/lib/python3.10/site-packages/dargs/dargs.py", line 349, in traverse_value
    self._traverse_sub(
  File "/root/deepmd-kit/lib/python3.10/site-packages/dargs/dargs.py", line 379, in _traverse_sub
    subarg.traverse(value, key_hook, value_hook, sub_hook, variant_hook, path)
  File "/root/deepmd-kit/lib/python3.10/site-packages/dargs/dargs.py", line 331, in traverse
    self.traverse_value(
  File "/root/deepmd-kit/lib/python3.10/site-packages/dargs/dargs.py", line 349, in traverse_value
    self._traverse_sub(
  File "/root/deepmd-kit/lib/python3.10/site-packages/dargs/dargs.py", line 379, in _traverse_sub
    subarg.traverse(value, key_hook, value_hook, sub_hook, variant_hook, path)
  File "/root/deepmd-kit/lib/python3.10/site-packages/dargs/dargs.py", line 331, in traverse
    self.traverse_value(
  File "/root/deepmd-kit/lib/python3.10/site-packages/dargs/dargs.py", line 349, in traverse_value
    self._traverse_sub(
  File "/root/deepmd-kit/lib/python3.10/site-packages/dargs/dargs.py", line 379, in _traverse_sub
    subarg.traverse(value, key_hook, value_hook, sub_hook, variant_hook, path)
  File "/root/deepmd-kit/lib/python3.10/site-packages/dargs/dargs.py", line 331, in traverse
    self.traverse_value(
  File "/root/deepmd-kit/lib/python3.10/site-packages/dargs/dargs.py", line 354, in traverse_value
    self._traverse_sub(
  File "/root/deepmd-kit/lib/python3.10/site-packages/dargs/dargs.py", line 378, in _traverse_sub
    for subarg in self.flatten_sub(value, path).values():
  File "/root/deepmd-kit/lib/python3.10/site-packages/dargs/dargs.py", line 303, in flatten_sub
    sub_dicts.extend(
  File "/root/deepmd-kit/lib/python3.10/site-packages/dargs/dargs.py", line 304, in <genexpr>
    vrnt.flatten_sub(value, path) for vrnt in self.sub_variants.values()
  File "/root/deepmd-kit/lib/python3.10/site-packages/dargs/dargs.py", line 816, in flatten_sub
    choice = self.get_choice(argdict, path)
  File "/root/deepmd-kit/lib/python3.10/site-packages/dargs/dargs.py", line 803, in get_choice
    raise ArgumentValueError(
dargs.dargs.ArgumentValueError: [at location `model/descriptor/list/1`] get invalid choice `se_uni` for flag key `type`.

### Steps to Reproduce

-

**Comment by njzjz** [comment] 2024-03-29 20:15
Duplicate of #3412

**Comment by njzjz** [comment] 2024-03-29 20:35
@wanghan-iapcm @iProzd Please check it

**Comment by wanghan-iapcm** [comment] 2024-04-03 00:17
your input script is not compatible with v3. please check v3's example.

**Comment by Andy6M** [comment] 2024-04-03 02:33
Successfully run using the following file https://github.com/deepmodeling/deepmd-kit/blob/v3.0.0a0/examples/water/dpa2/input_torch.json 
Does it support fine tuning using the following .pt file in this mode? https://www.aissquare.com/models/detail?pageType=models&name=DPA_v2.0.0&id=150

Thank you

**Comment by Andy6M** [comment] 2024-04-03 06:24
Well, it seems could not use the dpa-2 finetune .pt file in v3 directly.
My command is `dp --pt train input2.json --finetune model.pt`

The output is:
nohup: ignoring input
To get the best performance, it is recommended to adjust the number of threads by setting the environment variables OMP_NUM_THREADS, DP_INTRA_OP_PARALLELISM_THREADS, and DP_INTER_OP_PARALLELISM_THREADS. See https://deepmd.rtfd.io/parallelism/ for more information.
[2024-04-03 14:19:41,807] DEEPMD INFO    DeepMD version: 3.0.0a0
[2024-04-03 14:19:41,807] DEEPMD INFO    Configuration path: input2.json
[2024-04-03 14:19:41,929] DEEPMD INFO     _____               _____   __  __  _____           _     _  _   
[2024-04-03 14:19:41,929] DEEPMD INFO    |  __ \             |  __ \ |  \/  ||  __ \         | |   (_)| |  
[2024-04-03 14:19:41,929] DEEPMD INFO    | |  | |  ___   ___ | |__) || \  / || |  | | ______ | | __ _ | |_ 
[2024-04-03 14:19:41,929] DEEPMD INFO    | |  | | / _ \ / _ \|  ___/ | |\/| || |  | ||______|| |/ /| || __|
[2024-04-03 14:19:41,929] DEEPMD INFO    | |__| ||  __/|  __/| |     | |  | || |__| |        |   < | || |_ 
[2024-04-03 14:19:41,929] DEEPMD INFO    |_____/  \___| \___||_|     |_|  |_||_____/         |_|\_\|_| \__|
[2024-04-03 14:19:41,929] DEEPMD INFO    Please read and cite:
[2024-04-03 14:19:41,929] DEEPMD INFO    Wang, Zhang, Han and E, Comput.Phys.Comm. 228, 178-184 (2018)
[2024-04-03 14:19:41,929] DEEPMD INFO    Zeng et al, J. Chem. Phys., 159, 054801 (2023)
[2024-04-03 14:19:41,929] DEEPMD INFO    See https://deepmd.rtfd.io/credits/ for details.
[2024-04-03 14:19:41,929] DEEPMD INFO    ---------------------------------------------------------------------------
[2024-04-03 14:19:41,929] DEEPMD INFO    installed to:          /root/deepmd-kit/lib/python3.10/site-packages/deepmd
[2024-04-03 14:19:41,929] DEEPMD INFO    source:                
[2024-04-03 14:19:41,930] DEEPMD INFO    source brach:          HEAD
[2024-04-03 14:19:41,930] DEEPMD INFO    source commit:         50a7f35
[2024-04-03 14:19:41,930] DEEPMD INFO    source commit at:      2024-03-03 17:25:20 -0500
[2024-04-03 14:19:41,930] DEEPMD INFO    use float prec:        double
[2024-04-03 14:19:41,930] DEEPMD INFO    build variant:         cuda
[2024-04-03 14:19:41,930] DEEPMD INFO    Backend:               PyTorch
[2024-04-03 14:19:41,930] DEEPMD INFO    PT ver:                v2.0.0.post200-gc263bd43e8e
[2024-04-03 14:19:41,930] DEEPMD INFO    running on:            autodl-container-02c64f884c-f31affc0
[2024-04-03 14:19:41,930] DEEPMD INFO    computing device:      cuda:0
[2024-04-03 14:19:41,930] DEEPMD INFO    CUDA_VISIBLE_DEVICES:  unset
[2024-04-03 14:19:41,930] DEEPMD INFO    Count of visible GPUs: 1
[2024-04-03 14:19:41,930] DEEPMD INFO    num_intra_threads:     0
[2024-04-03 14:19:41,930] DEEPMD INFO    num_inter_threads:     0
[2024-04-03 14:19:41,930] DEEPMD INFO    ---------------------------------------------------------------------------
[2024-04-03 14:19:41,978] DEEPMD INFO    Calculate neighbor statistics... (add --skip-neighbor-stat to skip this step)
[2024-04-03 14:19:44,198] DEEPMD INFO    Adjust batch size from 1024 to 2048
[2024-04-03 14:19:45,469] DEEPMD INFO    Adjust batch size from 2048 to 4096
[2024-04-03 14:19:45,480] DEEPMD INFO    Adjust batch size from 4096 to 8192
[2024-04-03 14:19:45,498] DEEPMD INFO    Adjust batch size from 8192 to 16384
[2024-04-03 14:19:45,835] DEEPMD INFO    Adjust batch size from 16384 to 32768
[2024-04-03 14:19:53,171] DEEPMD INFO    training data with min nbor dist: 0.7261265532636292
[2024-04-03 14:19:53,171] DEEPMD INFO    training data with max nbor size: [335]
[2024-04-03 14:19:53,171] DEEPMD WARNING sel of type 0 is not enough! The expected value is not less than 335, but you set it to 120. The accuracy of your model may get worse.
[2024-04-03 14:19:54,226] DEEPMD INFO    Adjust batch size from 1024 to 2048
[2024-04-03 14:19:54,228] DEEPMD INFO    Adjust batch size from 2048 to 4096
[2024-04-03 14:19:54,235] DEEPMD INFO    Adjust batch size from 4096 to 8192
[2024-04-03 14:19:54,250] DEEPMD INFO    Adjust batch size from 8192 to 16384
[2024-04-03 14:19:54,309] DEEPMD INFO    Adjust batch size from 16384 to 32768
[2024-04-03 14:19:59,336] DEEPMD INFO    training data with min nbor dist: 0.7261265532636292
[2024-04-03 14:19:59,336] DEEPMD INFO    training data with max nbor size: [38]
[2024-04-03 14:19:59,565] DEEPMD WARNING The fitting net will be re-init instead of using that in the pretrained model! The bias_shift will be statistic!
[2024-04-03 14:19:59,565] DEEPMD INFO    Change the model configurations according to the model branch Domains_Alloy in the pretrained one...
[2024-04-03 14:19:59,592] DEEPMD INFO    Constructing DataLoaders from 210 systems
[2024-04-03 14:20:00,115] DEEPMD INFO    Constructing DataLoaders from 738 systems
Traceback (most recent call last):
  File "/root/deepmd-kit/bin/dp", line 10, in <module>
    sys.exit(main())
  File "/root/deepmd-kit/lib/python3.10/site-packages/deepmd/main.py", line 805, in main
    deepmd_main(args)
  File "/root/deepmd-kit/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/root/deepmd-kit/lib/python3.10/site-packages/deepmd/pt/entrypoints/main.py", line 308, in main
    train(FLAGS)
  File "/root/deepmd-kit/lib/python3.10/site-packages/deepmd/pt/entrypoints/main.py", line 270, in train
    trainer = get_trainer(
  File "/root/deepmd-kit/lib/python3.10/site-packages/deepmd/pt/entrypoints/main.py", line 187, in get_trainer
    trainer = training.Trainer(
  File "/root/deepmd-kit/lib/python3.10/site-packages/deepmd/pt/train/training.py", line 307, in __init__
    self.model = get_single_model(
  File "/root/deepmd-kit/lib/python3.10/site-packages/deepmd/pt/train/training.py", line 250, in get_single_model
    model = get_model(deepcopy(_model_params)).to(DEVICE)
  File "/root/deepmd-kit/lib/python3.10/site-packages/deepmd/pt/model/model/__init__.py", line 91, in get_model
    descriptor = BaseDescriptor(**model_params["descriptor"])
  File "/root/deepmd-kit/lib/python3.10/site-packages/deepmd/utils/plugin.py", line 88, in __call__
    obj.__init__(*args, **kwargs)
  File "/root/deepmd-kit/lib/python3.10/site-packages/deepmd/pt/model/descriptor/hybrid.py", line 68, in __init__
    BaseDescriptor(**ii, **kwargs)
  File "/root/deepmd-kit/lib/python3.10/site-packages/deepmd/utils/plugin.py", line 88, in __call__
    obj.__init__(*args, **kwargs)
TypeError: DescrptDPA1.__init__() got an unexpected keyword argument 'seed'

**Comment by njzjz** [comment] 2024-04-06 19:34
Yes, @wanghan-iapcm has answered in #3412.

@iProzd Could you add such information to the documentation of this model?

**Comment by njzjz** [comment] 2024-04-10 07:05
The documentation has been updated.

**Closed by njzjz** 2024-04-10 07:05 UTC
Labels: Docs
