### ISSUE TITLE
When I use dcu "dp train " , the lcurve.out file  occurs "nan" error.& I calculated the thermal conductivity with potential, and the result was 0.002, but the correct result was 2

### ISSUE THREAD

**Issue by qinmi-sudo** [deepmodeling/deepmd-kit#1164] opened 2021-09-22 23:29 UTC
1、 the lcurve.out file  occurs "nan" error.
![266293125597865023](https://user-images.githubusercontent.com/70270603/134434121-828bdf70-a3a5-4e16-a0fe-13f4c512a42b.png)
[bulk-train.zip](https://github.com/deepmodeling/deepmd-kit/files/7214363/bulk-train.zip)
2、 I calculated the thermal conductivity with potential, and the result was 0.002, but the correct result was about 2. When I use the same parameters and the result on the gpu is about 1.5.
[kappa.zip](https://github.com/deepmodeling/deepmd-kit/files/7214388/kappa.zip)

**Comment by denghuilu** [comment] 2021-09-24 06:06
It looks like an error occurred during the training process. The output of lcurve.out should not be nan. Which version of deepmd-kit are you using in the dcu environment?

**Comment by wankiwi** [comment] 2021-12-22 07:31
Can you give me some suggestions to install Deepmd-kit on a machine with DCU? I think I used the same cluster (HF Advanced Computing Center) with you : )
Thx~ My email is wankaiweii@gmail.com

**Comment by njzjz** [comment] 2022-01-09 06:41
@denghuilu The log shows he was using de45c24.

**Comment by njzjz** [comment] 2022-10-30 02:57
Not reproduced on MI100, with latest DeePMD-kit, ROCm 5.1.3, and TensorFlow 2.9.1.

[lcurve.out.txt](https://github.com/deepmodeling/deepmd-kit/files/9894980/lcurve.out.txt)

**Comment by njzjz** [comment] 2023-10-18 18:24
I'll close this issue since it cannot be reproduced. Feel free to reopen it if anyone can reproduce it and give more details.

**Closed by njzjz** 2023-10-18 18:24 UTC
Labels: bug, failed to reproduce
