### ISSUE TITLE
When using dp compression, I encountered the following error. My dataset is relatively large and I compressed it using a model after DEEPMD kit.

### ISSUE THREAD

**Issue by XuFanffei** [deepmodeling/deepmd-kit#2968] opened 2023-11-01 11:00 UTC
### Summary

The specific error message is as follows：
File "/opt/deepmd-kit-2.2.1/lib/python3.10/site-packages/tensorflow/python/training/saver.py", line 1324, in save
    self.export_meta_graph(
  File "/opt/deepmd-kit-2.2.1/lib/python3.10/site-packages/tensorflow/python/training/saver.py", line 1373, in export_meta_graph
    graph_def=ops.get_default_graph().as_graph_def(add_shapes=True),
  File "/opt/deepmd-kit-2.2.1/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 3568, in as_graph_def
    result, _ = self._as_graph_def(from_version, add_shapes)
  File "/opt/deepmd-kit-2.2.1/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 3482, in _as_graph_def
    graph.ParseFromString(compat.as_bytes(data))
google.protobuf.message.DecodeError: Error parsing message as the message exceeded the protobuf limit with type 'tensorflow.GraphDef'

### DeePMD-kit Version

2.2.1

### TensorFlow Version

2.9.0

### Details

I have referred to the following tutorials：https://zhuanlan.zhihu.com/p/406704835

**Comment by njzjz** [comment] 2023-11-01 19:39
Duplicate of #790

**Closed by njzjz** 2023-11-01 19:39 UTC
Labels: wontfix

**Comment by MingjieWen** [comment] 2023-11-02 09:37
thank you, jinzhe. I will check and try it.
