### ISSUE TITLE
DPA2 potential function problem

### ISSUE THREAD

**Issue by xwxwshi** [deepmodeling/deepmd-kit#3858] opened 2024-06-06 02:24 UTC
### Summary

I'm running lammps with DPA2's potential function and I get this error and it terminates, can you help me?

### DeePMD-kit Version

3.0

### Backend and its version

tensorflow 2.16.1

### Details

![wecom-temp-178265-f65d693b33d7cb6eea9b5c8114b030a6](https://github.com/deepmodeling/deepmd-kit/assets/170500277/df9c8723-a1f8-4673-bf91-8bd9cb729347)
![wecom-temp-476747-706b9ed4e4da362014789014a40633dc](https://github.com/deepmodeling/deepmd-kit/assets/170500277/a428491e-d164-41bc-938a-eba9db4d380d)

**Comment by iProzd** [comment] 2024-06-06 10:04
Which version are you using? Now **only built-from-source 2024Q1 branch and devel branch** support lammps for DPA2.
See 'How to use' section of [this page](https://aissquare.com/models/detail?pageType=models&name=DPA-2.1.0-2024Q1&id=244).

**Comment by njzjz** [comment] 2024-06-06 20:03
duplicate of #3428

**Closed** 2024-06-06 20:03 UTC
Labels: duplicate

**Comment by Zch102xjtumse** [comment] 2024-06-07 08:15
> D

Thanks!One small question is,did I just follow the Files changed section to fix?

**Comment by Zch102xjtumse** [comment] 2024-06-07 08:15
> Duplicate of #3428

Thanks!One small question is,did I just follow the Files changed section to fix?

**Comment by njzjz** [comment] 2024-06-08 23:20
> Thanks!One small question is,did I just follow the Files changed section to fix?

@iProzd has provided a good suggestion: https://github.com/deepmodeling/deepmd-kit/issues/3858#issuecomment-2151897505
