### ISSUE TITLE
dp train DeepSPIN.json:raise ArgumentValueError( dargs.dargs.ArgumentValueError: [at location `loss`] get invalid choice `ener_spin` for flag key `type`.

### ISSUE THREAD

**Issue by guanghuishi** [deepmodeling/deepmd-kit#3054] opened 2023-12-09 15:23 UTC
WARNING:tensorflow:From /data/home/siatghshi/anaconda3/envs/deepmd/lib/python3.10/site-packages/tensorflow/python/compat/v2_compat.py:107: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:root:To get the best performance, it is recommended to adjust the number of threads by setting the environment variables OMP_NUM_THREADS, TF_INTRA_OP_PARALLELISM_THREADS, and TF_INTER_OP_PARALLELISM_THREADS.
WARNING:root:Environment variable KMP_BLOCKTIME is empty. Use the default value 0
WARNING:root:Environment variable KMP_AFFINITY is empty. Use the default value granularity=fine,verbose,compact,1,0
/data/home/siatghshi/anaconda3/envs/deepmd/lib/python3.10/importlib/__init__.py:169: UserWarning: The NumPy module was reloaded (imported a second time). This can in some cases result in small but subtle issues and is discouraged.
  _bootstrap._exec(spec, module)
/data/home/siatghshi/anaconda3/envs/deepmd/lib/python3.10/site-packages/deepmd/utils/compat.py:316: UserWarning: It seems that you are using a deepmd-kit input of version 1.x.x, which is deprecated. we have converted the input to >2.0.0 compatible
  warnings.warn(msg)
Traceback (most recent call last):
  File "/data/home/siatghshi/anaconda3/envs/deepmd/bin/dp", line 10, in <module>
    sys.exit(main())
  File "/data/home/siatghshi/anaconda3/envs/deepmd/lib/python3.10/site-packages/deepmd/entrypoints/main.py", line 473, in main
    train_dp(**dict_args)
  File "/data/home/siatghshi/anaconda3/envs/deepmd/lib/python3.10/site-packages/deepmd/entrypoints/train.py", line 91, in train
    jdata = normalize(jdata)
  File "/data/home/siatghshi/anaconda3/envs/deepmd/lib/python3.10/site-packages/deepmd/utils/argcheck.py", line 722, in normalize
    data = base.normalize_value(data, trim_pattern="_*")
  File "/data/home/siatghshi/anaconda3/envs/deepmd/lib/python3.10/site-packages/dargs/dargs.py", line 554, in normalize_value
    self.traverse_value(
  File "/data/home/siatghshi/anaconda3/envs/deepmd/lib/python3.10/site-packages/dargs/dargs.py", line 342, in traverse_value
    self._traverse_sub(
  File "/data/home/siatghshi/anaconda3/envs/deepmd/lib/python3.10/site-packages/dargs/dargs.py", line 372, in _traverse_sub
    subarg.traverse(value, key_hook, value_hook, sub_hook, variant_hook, path)
  File "/data/home/siatghshi/anaconda3/envs/deepmd/lib/python3.10/site-packages/dargs/dargs.py", line 324, in traverse
    self.traverse_value(
  File "/data/home/siatghshi/anaconda3/envs/deepmd/lib/python3.10/site-packages/dargs/dargs.py", line 342, in traverse_value
    self._traverse_sub(
  File "/data/home/siatghshi/anaconda3/envs/deepmd/lib/python3.10/site-packages/dargs/dargs.py", line 371, in _traverse_sub
    for subarg in self.flatten_sub(value, path).values():
  File "/data/home/siatghshi/anaconda3/envs/deepmd/lib/python3.10/site-packages/dargs/dargs.py", line 296, in flatten_sub
    sub_dicts.extend(
  File "/data/home/siatghshi/anaconda3/envs/deepmd/lib/python3.10/site-packages/dargs/dargs.py", line 297, in <genexpr>
    vrnt.flatten_sub(value, path) for vrnt in self.sub_variants.values()
  File "/data/home/siatghshi/anaconda3/envs/deepmd/lib/python3.10/site-packages/dargs/dargs.py", line 809, in flatten_sub
    choice = self.get_choice(argdict, path)
  File "/data/home/siatghshi/anaconda3/envs/deepmd/lib/python3.10/site-packages/dargs/dargs.py", line 796, in get_choice
    raise ArgumentValueError(
dargs.dargs.ArgumentValueError: [at location `loss`] get invalid choice `ener_spin` for flag key `type`.

**Comment by njzjz** [comment] 2023-12-11 21:21
Close, as a duplicate of #3053.

**Closed by njzjz** 2023-12-11 21:21 UTC
Labels: duplicate
