### ISSUE TITLE
[BUG] dp compress error

### ISSUE THREAD

**Issue by qiurong13** [deepmodeling/deepmd-kit#1549] opened 2022-03-08 07:53 UTC
### Bug summary

successfully converted a model from v1.1 to new version, but fail to compress the new model, and the error is:
![8d967f8169668d5d488365f6f50e6ba4_](https://user-images.githubusercontent.com/46663128/157186682-2ec04dec-31c0-4a92-acda-6bc16a8eb310.png)

ps: i used this command: dp compress -t input.init.model.json -i in.pb -o out.pb, in which input.init.model.json is downloaded from DPlibrary, and training data is also downloaded.

### DeePMD-kit Version

2.0.3

### TensorFlow Version

2.5.0

### How did you download the software?

Offline packages

### Input Files, Running Commands, Error Log, etc.

covert command : dp convert-from 1.2 -i frozen_model.pb -o frozen_model-1.2.pb
compress command:  dp compress -t input.init.model.json -i frozen_model-1.2.pb  -o frozen_model-1.2-compress.pb
error log:
2022-03-08 15:03:54.953271: I tensorflow/stream_executor/platform/default/dso_loader.cc:53] Successfully opened dynamic library libcudart.so.10.1
WARNING:tensorflow:From /data/home/qiurong/software/deepmd-kit/lib/python3.9/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.v
ariable_scope) is deprecated and will be removed in a future version.Instructions for updating:
non-resource variables are not supported in the long term
WARNING:root:Environment variable KMP_BLOCKTIME is empty. Use the default value 0
WARNING:root:Environment variable KMP_AFFINITY is empty. Use the default value granularity=fine,verbose,compact,1,0
/data/home/qiurong/software/deepmd-kit/lib/python3.9/importlib/__init__.py:169: UserWarning: The NumPy module was reloaded (imported a second time). This can in some cases result in small b
ut subtle issues and is discouraged.  _bootstrap._exec(spec, module)
DEEPMD INFO    stage 0: compute the min_nbor_dist
Traceback (most recent call last):
  File "/data/home/qiurong/software/deepmd-kit/lib/python3.9/site-packages/deepmd/utils/graph.py", line 55, in get_tensor_by_name_from_graph
    tensor = graph.get_tensor_by_name(tensor_name + ':0')
  File "/data/home/qiurong/software/deepmd-kit/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 3931, in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
  File "/data/home/qiurong/software/deepmd-kit/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 3755, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/data/home/qiurong/software/deepmd-kit/lib/python3.9/site-packages/tensorflow/python/framework/ops.py", line 3795, in _as_graph_element_locked
    raise KeyError("The name %s refers to a Tensor which does not "
KeyError: "The name 'train_attr/training_script:0' refers to a Tensor which does not exist. The operation, 'train_attr/training_script', does not exist in the graph."

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/home/qiurong/software/deepmd-kit/lib/python3.9/site-packages/deepmd/entrypoints/compress.py", line 70, in compress
    t_jdata = get_tensor_by_name(input, 'train_attr/training_script')
  File "/data/home/qiurong/software/deepmd-kit/lib/python3.9/site-packages/deepmd/utils/graph.py", line 86, in get_tensor_by_name
    return get_tensor_by_name_from_graph(graph, tensor_name)
  File "/data/home/qiurong/software/deepmd-kit/lib/python3.9/site-packages/deepmd/utils/graph.py", line 57, in get_tensor_by_name_from_graph
    raise GraphWithoutTensorError() from e
deepmd.utils.errors.GraphWithoutTensorError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/home/qiurong/software/deepmd-kit/bin/dp", line 10, in <module>
    sys.exit(main())
  File "/data/home/qiurong/software/deepmd-kit/lib/python3.9/site-packages/deepmd/entrypoints/main.py", line 447, in main
    compress(**dict_args)
  File "/data/home/qiurong/software/deepmd-kit/lib/python3.9/site-packages/deepmd/entrypoints/compress.py", line 88, in compress
    t_min_nbor_dist = get_min_nbor_dist(jdata, get_rcut(jdata))
  File "/data/home/qiurong/software/deepmd-kit/lib/python3.9/site-packages/deepmd/entrypoints/train.py", line 284, in get_min_nbor_dist
    min_nbor_dist, _ = get_nbor_stat(jdata, rcut)
  File "/data/home/qiurong/software/deepmd-kit/lib/python3.9/site-packages/deepmd/entrypoints/train.py", line 255, in get_nbor_stat
    train_data = get_data(jdata["training"]["training_data"], max_rcut, type_map, None)
KeyError: 'training_data'

### Steps to Reproduce

...

**Comment by njzjz** [comment] 2022-03-08 18:44
It should have been fixed by #1297

**Comment by wanghan-iapcm** [comment] 2022-03-08 23:29
please try deepmd-kit v2.1.0

**Comment by lansekbaige** [comment] 2022-04-13 11:59
I meet the same problem, and I try it by deepmd-kit v2.1.0 , but the problem is also exit. 
Do you have any problems like this?
How to solve it？

**Comment by njzjz** [comment] 2022-04-14 05:30
This issue will be fixed by https://github.com/deepmodeling/deepmd-kit/pull/1633.

**Closed** 2022-04-14 19:10 UTC
Labels: bug
