### ISSUE TITLE
Fail to run MD simulation with DP (pytorch backend)

### ISSUE THREAD

**Issue by ZhihaoXu0313** [deepmodeling/deepmd-kit#3907] opened 2024-06-25 22:23 UTC
### Summary

Hi,

I encountered an issue when I was using DP for MD simulation (.pth model, from pytorch backend). The model can be successfully loaded but following the error:

![image](https://github.com/deepmodeling/deepmd-kit/assets/79070733/1295f3e2-260e-43f6-a761-023eb1213efe)
![image](https://github.com/deepmodeling/deepmd-kit/assets/79070733/3bb60db4-828d-4a8d-92c9-35dace63a639)

(sorry for the screen photo)

I wonder where could this issue coming from? Since the model seems to be good since it can be normally used for inference with Python API and there's no error occurs when using dp commands.

Best

### DeePMD-kit Version

DeePMD-kit v3.0.0a0

### Backend and its version

PyTorch

### Details

See above

**Comment by CaRoLZhangxy** [comment] 2024-06-26 02:13
MD simulation for dpa2 model is supported at 2024Q1 branch and multiprocess MD is supported at devel branch. Note that your model should be freeze with the same code version with your c++ inference code version. (Sometimes model trained with old version can not be freezed by a newer one )

**Comment by ZhihaoXu0313** [comment] 2024-06-26 02:41
Thank you so much for the response!

All of the works are under the same code (train, freeze, test, etc), so I guess there's no version issue at all. I'm now using the devel branch (I'll double check it later), so according to your information, it will be fine to use use that for MD simulation, right? What is the multiprocess MD simulation you meant?

Thanks again for your further explanation!

**Comment by njzjz** [comment] 2024-06-26 05:13
Duplicate of #3428

**Closed by njzjz** 2024-06-26 05:13 UTC
Labels: wontfix
