### ISSUE TITLE
‘se_uni’ in DPA-2 input.json

### ISSUE THREAD

**Issue by longkunxuluke** [deepmodeling/deepmd-kit#3595] opened 2024-03-25 09:08 UTC
### Summary

Hi, I am trying to use DPA-2. Following the example input.json in [section 3.2 here](https://nb.bohrium.dp.tech/detail/2649266844), I run the following command ```dp --pt train input.json --finetune model.pt```, where ```model.pt``` was taken from [here](https://www.aissquare.com/models/detail?pageType=models&name=DPA_v2.0.0&id=150). However I get the following error: ```dargs.dargs.ArgumentValueError: [at location `model/descriptor/list/1`] get invalid choice `se_uni` for flag key `type`.``` Is the input.json I used outdated now? 

### DeePMD-kit Version

DeepMD version: 3.0.0a0

### TensorFlow Version

Pytorch v2.0.0

### Python Version, CUDA Version, GCC Version, LAMMPS Version, etc

the default one in DPMD conda environment 

### Details

n/a

**Comment by njzjz** [comment] 2024-03-25 20:42
See https://github.com/deepmodeling/deepmd-kit/issues/3412#issuecomment-1979911920

**Comment by njzjz** [comment] 2024-03-25 20:43
Close as duplicate of #3412.

**Closed by njzjz** 2024-03-25 20:43 UTC
Labels: duplicate
