### ISSUE TITLE
[BUG] Error while training DPLR

### ISSUE THREAD

**Issue by siddarthachar** [deepmodeling/deepmd-kit#2842] opened 2023-09-19 11:22 UTC
### Bug summary

Error while training a DPLR model using a deepdipole model. I tried using the example for water in https://github.com/CSIprinceton/workshop-july-2023/tree/main/hands-on-sessions/day-3/8-deep-potential-long-range/1-train to make a deepdipole first and then a DPLR. The deepdipole was trained as per: https://github.com/CSIprinceton/workshop-july-2023/tree/main/hands-on-sessions/day-3/7-deep-wannier/2-train_dipole_model and it worked fine. I even tested these models to predict the atomic dipole moment vectors for water. However, training the DPLR gave this error: 

```
NotImplementedError: Cannot convert a symbolic Tensor (strided_slice_3:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported 
```

### DeePMD-kit Version

2.0.3

### TensorFlow Version

2?

### How did you download the software?

conda

### Input Files, Running Commands, Error Log, etc.

Input file: https://github.com/CSIprinceton/workshop-july-2023/blob/main/hands-on-sessions/day-3/8-deep-potential-long-range/1-train/input.json

Running Commands: dp train input.json

Error log: 
[slurm-624716.txt](https://github.com/deepmodeling/deepmd-kit/files/12659137/slurm-624716.txt)

### Steps to Reproduce

Use the files in https://github.com/CSIprinceton/workshop-july-2023/tree/main/hands-on-sessions/day-3/ to reproduce .pb files for DPLR training.

**Comment by Yi-FanLi** [comment] 2023-09-21 19:57
Hi Siddarth, 

Thanks for reporting this issue. I am so happy that you reach out to us after you go back from our workshop.

I have tried to reproduce your issue in my own environment. However, the training runs correctly on my side. 

From the information given in the issue, I do not have a clear idea on the reason of your issue. However, I suspect that the issue is because you are using an inappropriate environment. Specifically, it might be due to that the tensorflow version is improper. I suggest that you might create a new conda environment and install the newest release of deepmd-kit from the deepmodeling conda channel: https://anaconda.org/deepmodeling/deepmd-kit. 


Best,
Yifan

**Comment by njzjz** [comment] 2023-10-18 18:58
I'll close this issue since there is nothing wrong with the software.

@Yi-FanLi will answer the question.

**Closed by njzjz** 2023-10-18 18:58 UTC
Labels: failed to reproduce
