### ISSUE TITLE
[BUG] Tensorflow version is incompatible with deepmd kit

### ISSUE THREAD

**Issue by PolyuWeldingSpock** [deepmodeling/deepmd-kit#2863] opened 2023-09-26 02:47 UTC
### Bug summary

Hi everyone,

First I installed deepmd kit by:
```python
conda create -n deepmd deepmd-kit=2.2.4=*gpu libdeepmd=2.2.4=*gpu lammps horovod -c https://conda.deepmodeling.com -c defaults
``` 
Then I typed  `dp --version`, it showed:
`DeePMD-kit v2.2.5.dev58+gffe10f9d`  I think it is a little strange since I installed v2.2.4 deepmdkit.

Moreover, when  I tried to train my model with deepmd v2.2.4. It showed that my tensorflow version is not compatible with deepmd kit:
```python
WARNING:tensorflow:From /media/polyucmp/DATA/BIAN_Tieyuan/software/anaconda3/envs/deepmd/lib/python3.10/site-packages/tensorflow/python/compat/v2_compat.py:107: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:root:To get the best performance, it is recommended to adjust the number of threads by setting the environment variables OMP_NUM_THREADS, TF_INTRA_OP_PARALLELISM_THREADS, and TF_INTER_OP_PARALLELISM_THREADS. See https://deepmd.rtfd.io/parallelism/ for more information.
Traceback (most recent call last):
  File "/home/polyucmp/.local/lib/python3.10/site-packages/deepmd/env.py", line 387, in get_module
    module = tf.load_op_library(str(module_file))
  File "/media/polyucmp/DATA/BIAN_Tieyuan/software/anaconda3/envs/deepmd/lib/python3.10/site-packages/tensorflow/python/framework/load_library.py", line 54, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/polyucmp/.local/lib/python3.10/site-packages/deepmd/lib/libdeepmd_op.so: undefined symbol: _ZN3tsl7strings21FastInt32ToBufferLeftEiPc

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/media/polyucmp/DATA/BIAN_Tieyuan/software/anaconda3/envs/deepmd/bin/dp", line 10, in <module>
    sys.exit(main())
  File "/home/polyucmp/.local/lib/python3.10/site-packages/deepmd_cli/main.py", line 610, in main
    from deepmd.entrypoints.main import main as deepmd_main
  File "/home/polyucmp/.local/lib/python3.10/site-packages/deepmd/__init__.py", line 11, in <module>
    import deepmd.utils.network as network
  File "/home/polyucmp/.local/lib/python3.10/site-packages/deepmd/utils/__init__.py", line 3, in <module>
    from .data import (
  File "/home/polyucmp/.local/lib/python3.10/site-packages/deepmd/utils/data.py", line 12, in <module>
    from deepmd.env import (
  File "/home/polyucmp/.local/lib/python3.10/site-packages/deepmd/env.py", line 473, in <module>
    op_module = get_module("deepmd_op")
  File "/home/polyucmp/.local/lib/python3.10/site-packages/deepmd/env.py", line 415, in get_module
    raise RuntimeError(
RuntimeError: The version of TensorFlow used to compile this deepmd-kit package is 2.13.0, but the version of TensorFlow runtime you are using is 2.9.0. These two versions are incompatible and thus an error is raised when loading deepmd_op. You need to install TensorFlow 2.13.0, or rebuild deepmd-kit against TensorFlow 2.9.0.
If you are using a wheel from pypi, you may consider to install deepmd-kit execuating `pip install deepmd-kit --no-binary deepmd-kit` instead.
```
I tried to fix this by `pip install tensorflow==2.13.0`, but then it showed it cannot find my cuda driver and GPU. However, this problem did not happen before since I have used deepmd kit for some time.
```python
2023-09-26 10:01:18.196687: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-09-26 10:01:18.198473: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-09-26 10:01:18.236595: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-09-26 10:01:18.237241: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-09-26 10:01:18.777387: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
WARNING:tensorflow:From /media/polyucmp/DATA/BIAN_Tieyuan/software/anaconda3/envs/deepmd/lib/python3.10/site-packages/tensorflow/python/compat/v2_compat.py:107: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:root:To get the best performance, it is recommended to adjust the number of threads by setting the environment variables OMP_NUM_THREADS, TF_INTRA_OP_PARALLELISM_THREADS, and TF_INTER_OP_PARALLELISM_THREADS. See https://deepmd.rtfd.io/parallelism/ for more information.
WARNING:deepmd.train.run_options:Switch to serial execution due to lack of horovod module.
/home/polyucmp/.local/lib/python3.10/site-packages/deepmd/utils/compat.py:362: UserWarning: The argument training->numb_test has been deprecated since v2.0.0. Use training->validation_data->batch_size instead.
  warnings.warn(
DEEPMD INFO    Calculate neighbor statistics... (add --skip-neighbor-stat to skip this step)
2023-09-26 10:01:21.652944: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1960] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2023-09-26 10:01:21.740576: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:375] MLIR V1 optimization pass is not enabled
DEEPMD INFO    training data with min nbor dist: 2.696252635232834
DEEPMD INFO    training data with max nbor size: [ 8  8 14]
DEEPMD INFO     _____               _____   __  __  _____           _     _  _   
DEEPMD INFO    |  __ \             |  __ \ |  \/  ||  __ \         | |   (_)| |  
DEEPMD INFO    | |  | |  ___   ___ | |__) || \  / || |  | | ______ | | __ _ | |_ 
DEEPMD INFO    | |  | | / _ \ / _ \|  ___/ | |\/| || |  | ||______|| |/ /| || __|
DEEPMD INFO    | |__| ||  __/|  __/| |     | |  | || |__| |        |   < | || |_ 
DEEPMD INFO    |_____/  \___| \___||_|     |_|  |_||_____/         |_|\_\|_| \__|
DEEPMD INFO    Please read and cite:
DEEPMD INFO    Wang, Zhang, Han and E, Comput.Phys.Comm. 228, 178-184 (2018)
DEEPMD INFO    Zeng et al, J. Chem. Phys., 159, 054801 (2023)
DEEPMD INFO    See https://deepmd.rtfd.io/credits/ for details.
DEEPMD INFO    installed to:         /usr/local
DEEPMD INFO    source :              v2.2.4-58-gffe10f9d
DEEPMD INFO    source brach:         devel
DEEPMD INFO    source commit:        ffe10f9d
DEEPMD INFO    source commit at:     2023-09-25 12:56:32 +0800
DEEPMD INFO    build float prec:     double
DEEPMD INFO    build variant:        cpu
DEEPMD INFO    build with tf inc:    /tmp/pip-build-env-gl6oqbq2/normal/local/lib/python3.10/dist-packages/tensorflow/include;/tmp/pip-build-env-gl6oqbq2/normal/local/lib/python3.10/dist-packages/tensorflow/include
DEEPMD INFO    build with tf lib:    
DEEPMD INFO    ---Summary of the training---------------------------------------
DEEPMD INFO    running on:           polyucmp-HP-Z8-G4-Workstation
DEEPMD INFO    computing device:     cpu:0
DEEPMD INFO    CUDA_VISIBLE_DEVICES: unset
DEEPMD INFO    Count of visible GPU: 0
DEEPMD INFO    num_intra_threads:    0
DEEPMD INFO    num_inter_threads:    0
DEEPMD INFO    -----------------------------------------------------------------
2023-09-26 10:01:25.679564: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1960] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
DEEPMD INFO    ---Summary of DataSystem: training     -----------------------------------------------
DEEPMD INFO    found 38 system(s):
DEEPMD INFO                                        system  natoms  bch_sz   n_bch   prob  pbc
DEEPMD INFO                       ../data.init/init/cubic      40       1    1000  0.233    T
DEEPMD INFO                  ../data.init/init/tetragonal      80       1     300  0.070    T
DEEPMD INFO      ../data.iters/iter.000000/02.fp/data.000      40       1     100  0.023    T
DEEPMD INFO      ../data.iters/iter.000000/02.fp/data.001      40       1     100  0.023    T
DEEPMD INFO      ../data.iters/iter.000001/02.fp/data.002      40       1     150  0.035    T
DEEPMD INFO      ../data.iters/iter.000002/02.fp/data.005      40       1     150  0.035    T
DEEPMD INFO      ../data.iters/iter.000002/02.fp/data.003      40       1     150  0.035    T
DEEPMD INFO      ../data.iters/iter.000002/02.fp/data.004      40       1     150  0.035    T
DEEPMD INFO      ../data.iters/iter.000003/02.fp/data.008      40       1     200  0.047    T
DEEPMD INFO      ../data.iters/iter.000003/02.fp/data.009      40       1     200  0.047    T
DEEPMD INFO      ../data.iters/iter.000003/02.fp/data.000      40       1     200  0.047    T
DEEPMD INFO      ../data.iters/iter.000003/02.fp/data.007      40       1     200  0.047    T
DEEPMD INFO      ../data.iters/iter.000003/02.fp/data.005      40       1     200  0.047    T
DEEPMD INFO      ../data.iters/iter.000003/02.fp/data.001      40       1     200  0.047    T
DEEPMD INFO      ../data.iters/iter.000003/02.fp/data.003      40       1     200  0.047    T
DEEPMD INFO      ../data.iters/iter.000003/02.fp/data.006      40       1     200  0.047    T
DEEPMD INFO      ../data.iters/iter.000003/02.fp/data.004      40       1     200  0.047    T
DEEPMD INFO      ../data.iters/iter.000003/02.fp/data.002      40       1     200  0.047    T
DEEPMD INFO      ../data.iters/iter.000004/02.fp/data.008      40       1      10  0.002    T
DEEPMD INFO      ../data.iters/iter.000004/02.fp/data.009      40       1      10  0.002    T
DEEPMD INFO      ../data.iters/iter.000004/02.fp/data.000      40       1      10  0.002    T
DEEPMD INFO      ../data.iters/iter.000004/02.fp/data.007      40       1      10  0.002    T
DEEPMD INFO      ../data.iters/iter.000004/02.fp/data.005      40       1      10  0.002    T
DEEPMD INFO      ../data.iters/iter.000004/02.fp/data.001      40       1      10  0.002    T
DEEPMD INFO      ../data.iters/iter.000004/02.fp/data.003      40       1      10  0.002    T
DEEPMD INFO      ../data.iters/iter.000004/02.fp/data.006      40       1      10  0.002    T
DEEPMD INFO      ../data.iters/iter.000004/02.fp/data.004      40       1      10  0.002    T
DEEPMD INFO      ../data.iters/iter.000004/02.fp/data.002      40       1      10  0.002    T
DEEPMD INFO      ../data.iters/iter.000005/02.fp/data.008      40       1      10  0.002    T
DEEPMD INFO      ../data.iters/iter.000005/02.fp/data.009      40       1      10  0.002    T
DEEPMD INFO      ../data.iters/iter.000005/02.fp/data.000      40       1      10  0.002    T
DEEPMD INFO      ../data.iters/iter.000005/02.fp/data.007      40       1      10  0.002    T
DEEPMD INFO      ../data.iters/iter.000005/02.fp/data.005      40       1      10  0.002    T
DEEPMD INFO      ../data.iters/iter.000005/02.fp/data.001      40       1      10  0.002    T
DEEPMD INFO      ../data.iters/iter.000005/02.fp/data.003      40       1      10  0.002    T
DEEPMD INFO      ../data.iters/iter.000005/02.fp/data.006      40       1      10  0.002    T
DEEPMD INFO      ../data.iters/iter.000005/02.fp/data.004      40       1      10  0.002    T
DEEPMD INFO      ../data.iters/iter.000005/02.fp/data.002      40       1      10  0.002    T
DEEPMD INFO    --------------------------------------------------------------------------------------
DEEPMD INFO    training without frame parameter
DEEPMD INFO    data stating... (this step may take long time)
DEEPMD INFO    built lr
DEEPMD INFO    built network
DEEPMD INFO    built training
WARNING:root:To get the best performance, it is recommended to adjust the number of threads by setting the environment variables OMP_NUM_THREADS, TF_INTRA_OP_PARALLELISM_THREADS, and TF_INTER_OP_PARALLELISM_THREADS. See https://deepmd.rtfd.io/parallelism/ for more information.
2023-09-26 10:01:29.979246: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1960] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
DEEPMD INFO    initialize model from scratch
DEEPMD INFO    start training at lr 1.00e-03 (== 1.00e-03), decay_step 5000, decay_rate 0.944061, final lr will be 1.00e-08
WARNING:tensorflow:From /home/polyucmp/.local/lib/python3.10/site-packages/deepmd/train/trainer.py:1197: py_func (from tensorflow.python.ops.script_ops) is deprecated and will be removed in a future version.
Instructions for updating:
tf.py_func is deprecated in TF V2. Instead, there are two
    options available in V2.
    - tf.py_function takes a python function which manipulates tf eager
    tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
    an ndarray (just call tensor.numpy()) but having access to eager tensors
    means `tf.py_function`s can use accelerators such as GPUs as well as
    being differentiable using a gradient tape.
    - tf.numpy_function maintains the semantics of the deprecated tf.py_func
    (it is not differentiable, and manipulates numpy arrays). It drops the
    stateful argument making all functions stateful.
    
WARNING:tensorflow:From /home/polyucmp/.local/lib/python3.10/site-packages/deepmd/train/trainer.py:1197: py_func (from tensorflow.python.ops.script_ops) is deprecated and will be removed in a future version.
Instructions for updating:
tf.py_func is deprecated in TF V2. Instead, there are two
    options available in V2.
    - tf.py_function takes a python function which manipulates tf eager
    tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
    an ndarray (just call tensor.numpy()) but having access to eager tensors
    means `tf.py_function`s can use accelerators such as GPUs as well as
    being differentiable using a gradient tape.
    - tf.numpy_function maintains the semantics of the deprecated tf.py_func
    (it is not differentiable, and manipulates numpy arrays). It drops the
    stateful argument making all functions stateful.
    
2023-09-26 10:01:32.684416: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1960] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
``` 

I think there might be some issues in deepmd kit. Hope you can see it. Thanks!

### DeePMD-kit Version

2.2.4

### TensorFlow Version

2.9.0/2.13.0

### How did you download the software?

conda

### Input Files, Running Commands, Error Log, etc.

Bug 1
```python
WARNING:tensorflow:From /media/polyucmp/DATA/BIAN_Tieyuan/software/anaconda3/envs/deepmd/lib/python3.10/site-packages/tensorflow/python/compat/v2_compat.py:107: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:root:To get the best performance, it is recommended to adjust the number of threads by setting the environment variables OMP_NUM_THREADS, TF_INTRA_OP_PARALLELISM_THREADS, and TF_INTER_OP_PARALLELISM_THREADS. See https://deepmd.rtfd.io/parallelism/ for more information.
Traceback (most recent call last):
  File "/home/polyucmp/.local/lib/python3.10/site-packages/deepmd/env.py", line 387, in get_module
    module = tf.load_op_library(str(module_file))
  File "/media/polyucmp/DATA/BIAN_Tieyuan/software/anaconda3/envs/deepmd/lib/python3.10/site-packages/tensorflow/python/framework/load_library.py", line 54, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/polyucmp/.local/lib/python3.10/site-packages/deepmd/lib/libdeepmd_op.so: undefined symbol: _ZN3tsl7strings21FastInt32ToBufferLeftEiPc

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/media/polyucmp/DATA/BIAN_Tieyuan/software/anaconda3/envs/deepmd/bin/dp", line 10, in <module>
    sys.exit(main())
  File "/home/polyucmp/.local/lib/python3.10/site-packages/deepmd_cli/main.py", line 610, in main
    from deepmd.entrypoints.main import main as deepmd_main
  File "/home/polyucmp/.local/lib/python3.10/site-packages/deepmd/__init__.py", line 11, in <module>
    import deepmd.utils.network as network
  File "/home/polyucmp/.local/lib/python3.10/site-packages/deepmd/utils/__init__.py", line 3, in <module>
    from .data import (
  File "/home/polyucmp/.local/lib/python3.10/site-packages/deepmd/utils/data.py", line 12, in <module>
    from deepmd.env import (
  File "/home/polyucmp/.local/lib/python3.10/site-packages/deepmd/env.py", line 473, in <module>
    op_module = get_module("deepmd_op")
  File "/home/polyucmp/.local/lib/python3.10/site-packages/deepmd/env.py", line 415, in get_module
    raise RuntimeError(
RuntimeError: The version of TensorFlow used to compile this deepmd-kit package is 2.13.0, but the version of TensorFlow runtime you are using is 2.9.0. These two versions are incompatible and thus an error is raised when loading deepmd_op. You need to install TensorFlow 2.13.0, or rebuild deepmd-kit against TensorFlow 2.9.0.
If you are using a wheel from pypi, you may consider to install deepmd-kit execuating `pip install deepmd-kit --no-binary deepmd-kit` instead.
```
Bug 2
```python
2023-09-26 10:01:18.196687: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-09-26 10:01:18.198473: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-09-26 10:01:18.236595: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-09-26 10:01:18.237241: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-09-26 10:01:18.777387: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
WARNING:tensorflow:From /media/polyucmp/DATA/BIAN_Tieyuan/software/anaconda3/envs/deepmd/lib/python3.10/site-packages/tensorflow/python/compat/v2_compat.py:107: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:root:To get the best performance, it is recommended to adjust the number of threads by setting the environment variables OMP_NUM_THREADS, TF_INTRA_OP_PARALLELISM_THREADS, and TF_INTER_OP_PARALLELISM_THREADS. See https://deepmd.rtfd.io/parallelism/ for more information.
WARNING:deepmd.train.run_options:Switch to serial execution due to lack of horovod module.
/home/polyucmp/.local/lib/python3.10/site-packages/deepmd/utils/compat.py:362: UserWarning: The argument training->numb_test has been deprecated since v2.0.0. Use training->validation_data->batch_size instead.
  warnings.warn(
DEEPMD INFO    Calculate neighbor statistics... (add --skip-neighbor-stat to skip this step)
2023-09-26 10:01:21.652944: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1960] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2023-09-26 10:01:21.740576: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:375] MLIR V1 optimization pass is not enabled
DEEPMD INFO    training data with min nbor dist: 2.696252635232834
DEEPMD INFO    training data with max nbor size: [ 8  8 14]
DEEPMD INFO     _____               _____   __  __  _____           _     _  _   
DEEPMD INFO    |  __ \             |  __ \ |  \/  ||  __ \         | |   (_)| |  
DEEPMD INFO    | |  | |  ___   ___ | |__) || \  / || |  | | ______ | | __ _ | |_ 
DEEPMD INFO    | |  | | / _ \ / _ \|  ___/ | |\/| || |  | ||______|| |/ /| || __|
DEEPMD INFO    | |__| ||  __/|  __/| |     | |  | || |__| |        |   < | || |_ 
DEEPMD INFO    |_____/  \___| \___||_|     |_|  |_||_____/         |_|\_\|_| \__|
DEEPMD INFO    Please read and cite:
DEEPMD INFO    Wang, Zhang, Han and E, Comput.Phys.Comm. 228, 178-184 (2018)
DEEPMD INFO    Zeng et al, J. Chem. Phys., 159, 054801 (2023)
DEEPMD INFO    See https://deepmd.rtfd.io/credits/ for details.
DEEPMD INFO    installed to:         /usr/local
DEEPMD INFO    source :              v2.2.4-58-gffe10f9d
DEEPMD INFO    source brach:         devel
DEEPMD INFO    source commit:        ffe10f9d
DEEPMD INFO    source commit at:     2023-09-25 12:56:32 +0800
DEEPMD INFO    build float prec:     double
DEEPMD INFO    build variant:        cpu
DEEPMD INFO    build with tf inc:    /tmp/pip-build-env-gl6oqbq2/normal/local/lib/python3.10/dist-packages/tensorflow/include;/tmp/pip-build-env-gl6oqbq2/normal/local/lib/python3.10/dist-packages/tensorflow/include
DEEPMD INFO    build with tf lib:    
DEEPMD INFO    ---Summary of the training---------------------------------------
DEEPMD INFO    running on:           polyucmp-HP-Z8-G4-Workstation
DEEPMD INFO    computing device:     cpu:0
DEEPMD INFO    CUDA_VISIBLE_DEVICES: unset
DEEPMD INFO    Count of visible GPU: 0
DEEPMD INFO    num_intra_threads:    0
DEEPMD INFO    num_inter_threads:    0
DEEPMD INFO    -----------------------------------------------------------------
2023-09-26 10:01:25.679564: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1960] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
DEEPMD INFO    ---Summary of DataSystem: training     -----------------------------------------------
DEEPMD INFO    found 38 system(s):
DEEPMD INFO                                        system  natoms  bch_sz   n_bch   prob  pbc
DEEPMD INFO                       ../data.init/init/cubic      40       1    1000  0.233    T
DEEPMD INFO                  ../data.init/init/tetragonal      80       1     300  0.070    T
DEEPMD INFO      ../data.iters/iter.000000/02.fp/data.000      40       1     100  0.023    T
DEEPMD INFO      ../data.iters/iter.000000/02.fp/data.001      40       1     100  0.023    T
DEEPMD INFO      ../data.iters/iter.000001/02.fp/data.002      40       1     150  0.035    T
DEEPMD INFO      ../data.iters/iter.000002/02.fp/data.005      40       1     150  0.035    T
DEEPMD INFO      ../data.iters/iter.000002/02.fp/data.003      40       1     150  0.035    T
DEEPMD INFO      ../data.iters/iter.000002/02.fp/data.004      40       1     150  0.035    T
DEEPMD INFO      ../data.iters/iter.000003/02.fp/data.008      40       1     200  0.047    T
DEEPMD INFO      ../data.iters/iter.000003/02.fp/data.009      40       1     200  0.047    T
DEEPMD INFO      ../data.iters/iter.000003/02.fp/data.000      40       1     200  0.047    T
DEEPMD INFO      ../data.iters/iter.000003/02.fp/data.007      40       1     200  0.047    T
DEEPMD INFO      ../data.iters/iter.000003/02.fp/data.005      40       1     200  0.047    T
DEEPMD INFO      ../data.iters/iter.000003/02.fp/data.001      40       1     200  0.047    T
DEEPMD INFO      ../data.iters/iter.000003/02.fp/data.003      40       1     200  0.047    T
DEEPMD INFO      ../data.iters/iter.000003/02.fp/data.006      40       1     200  0.047    T
DEEPMD INFO      ../data.iters/iter.000003/02.fp/data.004      40       1     200  0.047    T
DEEPMD INFO      ../data.iters/iter.000003/02.fp/data.002      40       1     200  0.047    T
DEEPMD INFO      ../data.iters/iter.000004/02.fp/data.008      40       1      10  0.002    T
DEEPMD INFO      ../data.iters/iter.000004/02.fp/data.009      40       1      10  0.002    T
DEEPMD INFO      ../data.iters/iter.000004/02.fp/data.000      40       1      10  0.002    T
DEEPMD INFO      ../data.iters/iter.000004/02.fp/data.007      40       1      10  0.002    T
DEEPMD INFO      ../data.iters/iter.000004/02.fp/data.005      40       1      10  0.002    T
DEEPMD INFO      ../data.iters/iter.000004/02.fp/data.001      40       1      10  0.002    T
DEEPMD INFO      ../data.iters/iter.000004/02.fp/data.003      40       1      10  0.002    T
DEEPMD INFO      ../data.iters/iter.000004/02.fp/data.006      40       1      10  0.002    T
DEEPMD INFO      ../data.iters/iter.000004/02.fp/data.004      40       1      10  0.002    T
DEEPMD INFO      ../data.iters/iter.000004/02.fp/data.002      40       1      10  0.002    T
DEEPMD INFO      ../data.iters/iter.000005/02.fp/data.008      40       1      10  0.002    T
DEEPMD INFO      ../data.iters/iter.000005/02.fp/data.009      40       1      10  0.002    T
DEEPMD INFO      ../data.iters/iter.000005/02.fp/data.000      40       1      10  0.002    T
DEEPMD INFO      ../data.iters/iter.000005/02.fp/data.007      40       1      10  0.002    T
DEEPMD INFO      ../data.iters/iter.000005/02.fp/data.005      40       1      10  0.002    T
DEEPMD INFO      ../data.iters/iter.000005/02.fp/data.001      40       1      10  0.002    T
DEEPMD INFO      ../data.iters/iter.000005/02.fp/data.003      40       1      10  0.002    T
DEEPMD INFO      ../data.iters/iter.000005/02.fp/data.006      40       1      10  0.002    T
DEEPMD INFO      ../data.iters/iter.000005/02.fp/data.004      40       1      10  0.002    T
DEEPMD INFO      ../data.iters/iter.000005/02.fp/data.002      40       1      10  0.002    T
DEEPMD INFO    --------------------------------------------------------------------------------------
DEEPMD INFO    training without frame parameter
DEEPMD INFO    data stating... (this step may take long time)
DEEPMD INFO    built lr
DEEPMD INFO    built network
DEEPMD INFO    built training
WARNING:root:To get the best performance, it is recommended to adjust the number of threads by setting the environment variables OMP_NUM_THREADS, TF_INTRA_OP_PARALLELISM_THREADS, and TF_INTER_OP_PARALLELISM_THREADS. See https://deepmd.rtfd.io/parallelism/ for more information.
2023-09-26 10:01:29.979246: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1960] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
DEEPMD INFO    initialize model from scratch
DEEPMD INFO    start training at lr 1.00e-03 (== 1.00e-03), decay_step 5000, decay_rate 0.944061, final lr will be 1.00e-08
WARNING:tensorflow:From /home/polyucmp/.local/lib/python3.10/site-packages/deepmd/train/trainer.py:1197: py_func (from tensorflow.python.ops.script_ops) is deprecated and will be removed in a future version.
Instructions for updating:
tf.py_func is deprecated in TF V2. Instead, there are two
    options available in V2.
    - tf.py_function takes a python function which manipulates tf eager
    tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
    an ndarray (just call tensor.numpy()) but having access to eager tensors
    means `tf.py_function`s can use accelerators such as GPUs as well as
    being differentiable using a gradient tape.
    - tf.numpy_function maintains the semantics of the deprecated tf.py_func
    (it is not differentiable, and manipulates numpy arrays). It drops the
    stateful argument making all functions stateful.
    
WARNING:tensorflow:From /home/polyucmp/.local/lib/python3.10/site-packages/deepmd/train/trainer.py:1197: py_func (from tensorflow.python.ops.script_ops) is deprecated and will be removed in a future version.
Instructions for updating:
tf.py_func is deprecated in TF V2. Instead, there are two
    options available in V2.
    - tf.py_function takes a python function which manipulates tf eager
    tensors instead of numpy arrays. It's easy to convert a tf eager tensor to
    an ndarray (just call tensor.numpy()) but having access to eager tensors
    means `tf.py_function`s can use accelerators such as GPUs as well as
    being differentiable using a gradient tape.
    - tf.numpy_function maintains the semantics of the deprecated tf.py_func
    (it is not differentiable, and manipulates numpy arrays). It drops the
    stateful argument making all functions stateful.
    
2023-09-26 10:01:32.684416: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1960] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
``` 

### Steps to Reproduce

Bug 1:

```python
conda create -n deepmd deepmd-kit=2.2.4=*gpu libdeepmd=2.2.4=*gpu lammps horovod -c https://conda.deepmodeling.com -c defaults
``` 
Then run `dp train input.json`

Bug 2：
In conda deepmd env
`pip uninstall tensorflow`
`pip install tensorflow==2.13.0`
`dp train input.json`

**Comment by njzjz** [comment] 2023-09-26 03:50
Duplicate of #2533

**Comment by PolyuWeldingSpock** [comment] 2023-09-26 04:32
> Duplicate of #2533

Thanks!

**Closed** 2023-09-26 06:37 UTC
Labels: duplicate
