### ISSUE TITLE
Does LAMMPS support efield with deepmd models (.pb format) potentials?

### ISSUE THREAD

**Issue by karvs25** [deepmodeling/deepmd-kit#4158] opened 2024-09-23 09:14 UTC
### Summary

I used the DeePMD kit to generate a neural network potential frozen in the .pb format for the H2O molecules. I have created this and I wanted to study these potentials using with and without electric field. I have used

pair_style deepmd graph.pb # DeepMD-kit model file for water
pair_coeff * * # Apply the DeepMD-kit model to all atoms

It ran without any errors or warnings. But the results I got from these are the same. No change in the energy with respect to the temperature and pressure. I want to know if there is an effect of Efield using deepmd potentials in LAMMPS or if we need to use some alternative method to do it. Because I want to study the dynamics of some systems with deep neural network potentials in the presence of an electric field.

Recently, I came across this paper, which deals with the change of the bonds with respect to the electric field. They have used CP2K to generate data for the DeePMD kit and used that data in LAMMPS. They have studied the system with respect to different electric fields. Any commends on this? https://pubs.rsc.org/en/content/articlelanding/2024/cp/d3cp06202c

### DeePMD-kit Version

DeePMD-kit v2.2.11

### Backend and its version

TensorFlow v2.16.2

### Python Version, CUDA Version, GCC Version, LAMMPS Version, etc

Python 3.12.3
CUDA V12.6.68
GCC 13.2.0

### Details

I want to know dp model has information about charges or not?

**Comment by njzjz** [comment] 2024-09-28 22:18
The electric field in LAMMPS does not have an effect on deep potential models.

**Comment by njzjz** [comment] 2024-09-28 22:18
Duplicate of #1210

**Closed** 2024-10-01 19:59 UTC
Labels: wontfix
