### ISSUE TITLE
Appeal to a higher version of water's deep potential

### ISSUE THREAD

**Issue by lansekbaige** [deepmodeling/deepmd-kit#1630] opened 2022-04-13 09:37 UTC
### Summary

The current version of the water's deep potential on DPlibrary is V1.1. 
The version is too low to do dp compress. Would you can provide a higher version for me or provide me a  method to realize compress ?
Thanks very much.

### DeePMD-kit Version

2.1.0

### TensorFlow Version

2.7

### Details

We want to use the deep potential of the water on the DPlibrary. 
 This is the link: https://dplibrary.deepmd.net//#/project_details?project_id=202010.001
The current version of the water's deep potential on DPlibrary is V1.1.
But the version is too low to do dp compress. Would you can provide a higher version for me or provide me a  method to realize compress the model ?
Thanks very much.

**Comment by njzjz** [comment] 2022-04-13 20:36
You can use `dp convert-from` to convert models.

Note that v1.1 model and v1.2 model are the same things.

**Comment by Msunshinep** [comment] 2022-04-14 02:05
Thanks for your timely reply! Yes, the v1.1 model can be converted to the high version by using "dp convert-from". However, we found that the high version model converted from v1.1  cannot be compressed and something wrong will occur like:"[BUG] dp compress error · Issue #1549 · deepmodeling/deepmd-kit · GitHub". Moreover, such an error cannot be fixed by the "deepmd-kit v2.1.0" or our attempt for "updata_deepmd_input when compress #1297".
Therefore, we would like to ask for your help to fix this problem or provide the higher version model for water.
Thank you again for your help!

**Comment by Msunshinep** [comment] 2022-04-14 02:07
> Thanks for your timely reply! Yes, the v1.1 model can be converted to the high version by using "dp convert-from". However, we found that the high version model converted from v1.1 cannot be compressed and something wrong will occur like:"[BUG] dp compress error · Issue #1549 · deepmodeling/deepmd-kit · GitHub". Moreover, such an error cannot be fixed by the "deepmd-kit v2.1.0" or our attempt for "updata_deepmd_input when compress #1297". Therefore, we would like to ask for your help to fix this problem or provide the higher version model for water. Thank you again for your help!

**Comment by Msunshinep** [comment] 2022-04-14 02:07
> You can use `dp convert-from` to convert models.
> 
> Note that v1.1 model and v1.2 model are the same things.

Thanks for your timely reply! Yes, the v1.1 model can be converted to the high version by using "dp convert-from". However, we found that the high version model converted from v1.1 cannot be compressed and something wrong will occur like:"[BUG] dp compress error · Issue https://github.com/deepmodeling/deepmd-kit/issues/1549 · deepmodeling/deepmd-kit · GitHub". Moreover, such an error cannot be fixed by the "deepmd-kit v2.1.0" or our attempt for "updata_deepmd_input when compress https://github.com/deepmodeling/deepmd-kit/pull/1297".
Therefore, we would like to ask for your help to fix this problem or provide the higher version model for water.
Thank you again for your help!

**Comment by njzjz** [comment] 2022-04-14 04:26
#1549 was caused by an incompatible input file. What the input did you provide to `dp compress`?

**Comment by lansekbaige** [comment] 2022-04-14 05:03
Thanks for your reply!
We used the input file which down load from the DP Library .This is the link https://dplibrary.deepmd.net//#/project_details?project_id=202010.001
The details are as follows：
[input.init.model.json-txt.txt](https://github.com/deepmodeling/deepmd-kit/files/8486282/input.init.model.json-txt.txt)
We also try to delete the  "load_ckpt" in the input.json, but the model still can't be compressed  .
Thanks for your help!
@njzjz

**Comment by lansekbaige** [comment] 2022-04-14 05:05
Thanks for your reply!
We used the input file which down load from the DP Library .This is the link https://dplibrary.deepmd.net//#/project_details?project_id=202010.001
The details are as follows：
[input.init.model.json-txt.txt](https://github.com/deepmodeling/deepmd-kit/files/8486282/input.init.model.json-txt.txt)
We also try to delete the "load_ckpt" in the input.json, but the model still can't be compressed .
Thanks for your help!
> #1549 was caused by an incompatible input file. What the input file did you provide to `dp compress`?

**Comment by njzjz** [comment] 2022-04-14 05:30
#1549 should be fixed by #1633.

**Closed** 2022-04-14 19:10 UTC
Labels: duplicate
