### ISSUE TITLE
Error dp test

### ISSUE THREAD

**Issue by wjinjin** [deepmodeling/deepmd-kit#165] opened 2020-01-29 16:31 UTC
The erros shows as follow:
Traceback (most recent call last):
  File "/soft/anaconda3/bin/dp", line 10, in <module>
    sys.exit(main())
  File "/soft/anaconda3/lib/python3.7/site-packages/deepmd/main.py", line 69, in main
    test(args)
  File "/soft/anaconda3/lib/python3.7/site-packages/deepmd/test.py", line 20, in test
    test_ener(args)
  File "/soft/anaconda3/lib/python3.7/site-packages/deepmd/test.py", line 64, in test_ener
    l2e = (l2err (energy - test_data["energy"][:numb_test].reshape([-1,1])))
KeyError: 'energy'

**Comment by njzjz** [comment] 2020-01-29 17:06
Hi, what is your test data like? Does it contain `energy.npy`?

**Comment by wjinjin** [comment] 2020-01-29 18:15
I checked and energy.npy file exists.

**Comment by njzjz** [comment] 2020-01-30 18:20
It is confirmed as a bug caused by https://github.com/deepmodeling/deepmd-kit/commit/5f770195991ee3cbb5a741e6020b35503aeb3436.

**Comment by wjinjin** [comment] 2020-01-30 22:35
Now is there any way I can fix it? I already tried installing it again, but it still doesn't work.

**Comment by njzjz** [comment] 2020-01-31 19:29
> Now is there any way I can fix it? I already tried installing it again, but it still doesn't work.

It has been already fixed by #166 and #167. You can `git pull` to the newest version and reinstall it. (Or just replace `/soft/anaconda3/lib/python3.7/site-packages/deepmd/test.py` with the newest `test.py` file)
https://github.com/deepmodeling/deepmd-kit/blob/88da7169bb97bf91f0e9add8785cc307df8a10b6/source/train/test.py#L37-L47

**Closed** 2020-02-28 09:32 UTC
Labels: bug
